import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import authRoutes from './src/routes/authRoutes.js';
import aiRoutes from './src/routes/aiRoutes.js';
import adsRoutes from './src/routes/adsRoutes.js';
dotenv.config();
const app = express();
app.use(cors());
app.use(express.json());
app.get('/', (req, res) => res.send('⚔️ Vikingo Ads Brain™ Backend ativo e pronto para batalha!'));
app.use('/api/auth', authRoutes);
app.use('/api/ai', aiRoutes);
app.use('/api/ads', adsRoutes);
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`Servidor rodando na porta ${PORT}`));
